<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Description>MonoGame Content building task.</Description>
		<Authors>Simon Condon</Authors>
		<Copyright>2026 Simon Condon</Copyright>

		<!-- NB: timestamp below doesn't include seconds because depending on such a package gets VS into an infinite restore loop.. -->
		<Version>0.0.0-local.$([System.DateTime]::Now.ToString(yyMMddTHHmm))</Version>
		<!-- Will make this cleverer if anyone else starts contributing to this (look for local package sources with Powershell, maybe?) -->
		<LocalPackageSource>$(UserProfile)\Coding\Packages</LocalPackageSource>
	</PropertyGroup>

	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' != 'true' And Exists('$(LocalPackageSource)')">
		<PackageOutputPath>$(LocalPackageSource)</PackageOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<!-- weird prerelease version because latest version of MonoGame.Framework.Content.Pipeline currently needs it -->
		<PackageReference Include="Microsoft.Build.Utilities.Core" PrivateAssets="all" Version="18.9.6" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" PrivateAssets="all" Version="5.9.0" />
		<PackageReference Include="MonoGame.Framework" PrivateAssets="all" Version="3.8.5.1" />
		<PackageReference Include="MonoGame.Framework.Content.Pipeline" PrivateAssets="all" Version="3.8.*" />
		<!-- Override Microsoft.NETCore.App version that MonoGame.Framework.Content.Pipeline depends on - it has a severe vuln: -->
		<PackageReference Include="Microsoft.NETCore.App" PrivateAssets="all" Version="2.2.8" />
	</ItemGroup>
	
	<ItemGroup>
		<None Include="_PackageFiles\**\*" Pack="true" PackagePath="\" />
	</ItemGroup>

	<!-- The rest of the file is specific to this being a Nuget package that affects the MSBuild process.
	     It's based on guidance here: https://learn.microsoft.com/en-us/visualstudio/msbuild/tutorial-custom-task-code-generation?view=visualstudio -->
	
	<PropertyGroup>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<GenerateDependencyFile>true</GenerateDependencyFile>

		<!-- This property controls the targets that will run when MSBuild is collecting the files to be packaged. 
		     By adding our target (implemented below) to it, we hook ourselves into the process in a supported way. -->
		<TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
		
		<!-- This property tells MSBuild where the root folder of the package's build assets should be. 
		     Because we are not a library package, we should not pack to 'lib'. -->
		<BuildOutputTargetFolder>build\tasks</BuildOutputTargetFolder>
		
		<!-- NuGet does validation that libraries in a package are exposed as dependencies, 
		     but we _explicitly_ do not want that behavior for MSBuild tasks. 
		     They are isolated by design. Therefore we ignore this specific warning: -->
		<NoWarn>NU5100</NoWarn>
		
		<!-- Suppress NuGet warning NU5128. -->
		<SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
	</PropertyGroup>
	
	<!-- This is the target we defined above. Its purpose is to add all of our PackageReference and ProjectReference's runtime assets to our package output. -->
	<Target Name="CopyProjectReferencesToPackage" DependsOnTargets="ResolveReferences">
		<ItemGroup>
			<!-- The TargetPath is the path inside the package that the source file will be placed.
			     This is already precomputed in the ReferenceCopyLocalPaths items' DestinationSubPath, so reuse it here. -->
			<BuildOutputInPackage Include="@(ReferenceCopyLocalPaths)" TargetPath="%(ReferenceCopyLocalPaths.DestinationSubPath)" />

			<!--<BuildOutputInPackage Include="$(OutputPath)$(MSBuildThisFileName).runtimeconfig.json" />-->
			<BuildOutputInPackage Include="$(OutputPath)$(MSBuildThisFileName).deps.json" />
		</ItemGroup>
	</Target>

</Project>
