<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Description>MonoGame Content building task.</Description>
		<Authors>Simon Condon</Authors>
		<Copyright>2026 Simon Condon</Copyright>

		<!-- NB: timestamp below doesn't include seconds because depending on such a package gets VS into an infinite restore loop.. -->
		<Version>0.0.0-local.$([System.DateTime]::Now.ToString(yyMMddTHHmm))</Version>
		<!-- Will make this cleverer if anyone else starts contributing to this (look for local package sources with Powershell, maybe?) -->
		<LocalPackageSource>$(UserProfile)\Coding\Packages</LocalPackageSource>
	</PropertyGroup>

	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' != 'true' And Exists('$(LocalPackageSource)')">
		<PackageOutputPath>$(LocalPackageSource)</PackageOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Build.Utilities.Core" PrivateAssets="all" Version="18.9.6" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" PrivateAssets="all" Version="5.9.0" />
		<PackageReference Include="MonoGame.Framework" PrivateAssets="all" Version="3.8.5.1" />
		<PackageReference Include="MonoGame.Framework.Content.Pipeline" PrivateAssets="all" Version="3.8.*" />
		<!-- Override Microsoft.NETCore.App version that MonoGame.Framework.Content.Pipeline depends on - it has a severe vuln: -->
		<PackageReference Include="Microsoft.NETCore.App" PrivateAssets="all" Version="2.2.8" />
	</ItemGroup>
	
	<ItemGroup>
		<None Include="_PackageFiles\**\*" Pack="true" PackagePath="\" />
	</ItemGroup>

	<!-- 
	    This next section is specific to this being a Nuget package that affects the MSBuild process.
	    It's based on guidance here: https://learn.microsoft.com/en-us/visualstudio/msbuild/tutorial-custom-task-code-generation?view=visualstudio
	-->
	<PropertyGroup>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<GenerateDependencyFile>true</GenerateDependencyFile>

		<!-- This property controls the targets that will run when MSBuild is collecting the files to be packaged. 
		     By adding our target (implemented below) to it, we hook ourselves into the process in a supported way. -->
		<TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
		
		<!-- This property tells MSBuild where the root folder of the package's build assets should be. 
		     Because we are not a library package, we should not pack to 'lib'. -->
		<BuildOutputTargetFolder>build\tasks</BuildOutputTargetFolder>
		
		<!-- NuGet does validation that libraries in a package are exposed as dependencies, 
		     but we _explicitly_ do not want that behavior for MSBuild tasks. 
		     They are isolated by design. Therefore we ignore this specific warning: -->
		<NoWarn>NU5100</NoWarn>
		
		<!-- Suppress NuGet warning NU5128. -->
		<SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
	</PropertyGroup>
	<Target Name="CopyProjectReferencesToPackage" DependsOnTargets="ResolveReferences">
		<ItemGroup>
			<!-- The TargetPath is the path inside the package that the source file will be placed.
			     This is already precomputed in the ReferenceCopyLocalPaths items' DestinationSubPath, so reuse it here. -->
			<BuildOutputInPackage Include="@(ReferenceCopyLocalPaths)" TargetPath="%(ReferenceCopyLocalPaths.DestinationSubPath)" />

			<BuildOutputInPackage Include="$(OutputPath)$(MSBuildThisFileName).deps.json" />
		</ItemGroup>
	</Target>
	
	<!--
		MonoGame.Tool.* adds the binaries as content of consuming project - which isn't useful here (one wonders why these aren't done
		as runtimes - which is after all what they are). To work around, we take an explicit dependency to give us a path property,
		turn off the addition of content that they do (DisableMonoGameToolAssets), and instead manually copy into the package using a 
		target that we specify with the TargetsForTfmSpecificContentInPackage property.
	-->
	<ItemGroup>
		<PackageReference Include="MonoGame.Tool.Basisu" PrivateAssets="all" Version="2.0.2.1" GeneratePathProperty="true" />
		<PackageReference Include="MonoGame.Tool.Crunch" PrivateAssets="all" Version="1.0.4.7" GeneratePathProperty="true" />
		<PackageReference Include="MonoGame.Tool.Dxc" PrivateAssets="all" Version="1.9.2607.1" GeneratePathProperty="true" />
		<PackageReference Include="MonoGame.Tool.FFmpeg" PrivateAssets="all" Version="7.0.0.10" GeneratePathProperty="true" />
		<PackageReference Include="MonoGame.Tool.FFprobe" PrivateAssets="all" Version="7.0.0.10" GeneratePathProperty="true" />
	</ItemGroup>
	<PropertyGroup>
		<DisableMonoGameToolAssets>True</DisableMonoGameToolAssets>
		<TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);CopyToolsToPackage</TargetsForTfmSpecificContentInPackage>
	</PropertyGroup>
	<Target Name="CopyToolsToPackage" DependsOnTargets="ResolveReferences">
		<ItemGroup>
			<!--I'd LOVE to be able to use the recursive dir match stuff here to make this group much smaller,
			    but for some reason MSBuild gets *very* confused by having more than one item with a %RecursiveDir in it -->
			<!--<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Basisu)\binaries\**\*" PackagePath="build\tasks\$(TargetFramework)\%(RecursiveDir)%(Filename)%(Extension)" />-->
			<!--<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Crunch)\binaries\**\*" PackagePath="build\tasks\$(TargetFramework)\%(RecursiveDir)%(Filename)%(Extension)" />-->
			<!--<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Dxc)\binaries\**\*" PackagePath="build\tasks\$(TargetFramework)\%(RecursiveDir)%(Filename)%(Extension)" />-->
			<!--<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_FFmpeg)\binaries\**\*" PackagePath="build\tasks\$(TargetFramework)\%(RecursiveDir)%(Filename)%(Extension)" />-->
			<!--<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_FFprobe)\binaries\**\*" PackagePath="build\tasks\$(TargetFramework)\%(RecursiveDir)%(Filename)%(Extension)" />-->

			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Basisu)\binaries\linux-arm64\*" PackagePath="build\tasks\$(TargetFramework)\linux-arm64\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Basisu)\binaries\linux-x64\*" PackagePath="build\tasks\$(TargetFramework)\linux-x64\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Basisu)\binaries\osx\*" PackagePath="build\tasks\$(TargetFramework)\osx\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Basisu)\binaries\windows-arm64\*" PackagePath="build\tasks\$(TargetFramework)\windows-arm64\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Basisu)\binaries\windows-x64\*" PackagePath="build\tasks\$(TargetFramework)\windows-x64\" />

			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Crunch)\binaries\linux-arm64\*" PackagePath="build\tasks\$(TargetFramework)\linux-arm64\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Crunch)\binaries\linux-x64\*" PackagePath="build\tasks\$(TargetFramework)\linux-x64\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Crunch)\binaries\osx\*" PackagePath="build\tasks\$(TargetFramework)\osx\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Crunch)\binaries\windows-arm64\*" PackagePath="build\tasks\$(TargetFramework)\windows-arm64\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Crunch)\binaries\windows-x64\*" PackagePath="build\tasks\$(TargetFramework)\windows-x64\" />

			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Dxc)\binaries\linux-arm64\bin\*" PackagePath="build\tasks\$(TargetFramework)\linux-arm64\bin\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Dxc)\binaries\linux-arm64\lib\*" PackagePath="build\tasks\$(TargetFramework)\linux-arm64\lib\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Dxc)\binaries\linux-x64\bin\*" PackagePath="build\tasks\$(TargetFramework)\linux-x64\bin\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Dxc)\binaries\linux-x64\lib\*" PackagePath="build\tasks\$(TargetFramework)\linux-x64\lib\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Dxc)\binaries\osx\bin\*" PackagePath="build\tasks\$(TargetFramework)\osx\bin\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Dxc)\binaries\osx\lib\*" PackagePath="build\tasks\$(TargetFramework)\osx\lib\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Dxc)\binaries\windows-arm64\*" PackagePath="build\tasks\$(TargetFramework)\windows-arm64\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_Dxc)\binaries\windows-x64\*" PackagePath="build\tasks\$(TargetFramework)\windows-x64\" />

			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_FFmpeg)\binaries\linux-arm64\*" PackagePath="build\tasks\$(TargetFramework)\linux-arm64\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_FFmpeg)\binaries\linux-x64\*" PackagePath="build\tasks\$(TargetFramework)\linux-x64\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_FFmpeg)\binaries\osx\*" PackagePath="build\tasks\$(TargetFramework)\osx\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_FFmpeg)\binaries\windows-arm64\*" PackagePath="build\tasks\$(TargetFramework)\windows-arm64\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_FFmpeg)\binaries\windows-x64\*" PackagePath="build\tasks\$(TargetFramework)\windows-x64\" />

			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_FFprobe)\binaries\linux-arm64\*" PackagePath="build\tasks\$(TargetFramework)\linux-arm64\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_FFprobe)\binaries\linux-x64\*" PackagePath="build\tasks\$(TargetFramework)\linux-x64\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_FFprobe)\binaries\osx\*" PackagePath="build\tasks\$(TargetFramework)\osx\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_FFprobe)\binaries\windows-arm64\*" PackagePath="build\tasks\$(TargetFramework)\windows-arm64\" />
			<TfmSpecificPackageFile Include="$(PkgMonoGame_Tool_FFprobe)\binaries\windows-x64\*" PackagePath="build\tasks\$(TargetFramework)\windows-x64\" />
			
		</ItemGroup>
	</Target>
</Project>
