<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Description>MonoGame Content building task.</Description>
		<Authors>Simon Condon</Authors>
		<Copyright>2026 Simon Condon</Copyright>

		<!-- NB: timestamp below doesn't include seconds because depending on such a package gets VS into an infinite restore loop.. -->
		<Version>0.0.0-local.$([System.DateTime]::Now.ToString(yyMMddTHHmm))</Version>
		<!-- Will make this cleverer if anyone else starts contributing to this (look for local package sources with Powershell, maybe?) -->
		<LocalPackageSource>$(UserProfile)\Coding\Packages</LocalPackageSource>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' != 'true' And Exists('$(LocalPackageSource)')">
		<PackageOutputPath>$(LocalPackageSource)</PackageOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<!-- Override version Content.Pipeline depends on - it has a severe vuln: -->
		<PackageReference Include="Microsoft.NETCore.App" Version="2.2.8" />
		<PackageReference Include="MonoGame.Framework.Content.Pipeline" Version="3.8.*" />
	</ItemGroup>

</Project>
