<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../Exe.props" />
	
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<RollForward>Major</RollForward>
		<PublishReadyToRun>false</PublishReadyToRun>
		<TieredCompilation>false</TieredCompilation>
	</PropertyGroup>
	<PropertyGroup>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>Icon.ico</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="Icon.ico" />
		<None Remove="Icon.bmp" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Icon.ico">
			<LogicalName>Icon.ico</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Icon.bmp">
			<LogicalName>Icon.bmp</LogicalName>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<!-- NB: Need to reference the package, not the project - but also to include 
		     a project reference to ensure that they build in the correct order: -->
		<ProjectReference Include="..\SCMonoGame.MSBuildContentBuilder\SCMonoGame.MSBuildContentBuilder.csproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
		<PackageReference Include="SCMonoGame.MSBuildContentBuilder" Version="0.0.0-local.*" />
		
		<PackageReference Include="MonoGame.Framework" Version="3.8.*" />

	</ItemGroup>
	<ItemGroup Condition="'$(MonoGamePlatform)' == 'DesktopVK'">
		<PackageReference Include="MonoGame.Runtime.Mac.Vulkan" Version="3.8.*" />
		<PackageReference Include="MonoGame.Runtime.Linux.Vulkan" Version="3.8.*" />
		<PackageReference Include="MonoGame.Runtime.Windows.Vulkan" Version="3.8.*" />
	</ItemGroup>
	<ItemGroup Condition="'$(MonoGamePlatform)' == 'WindowsDX12'">
		<PackageReference Include="MonoGame.Runtime.Windows.DX12" Version="3.8.*" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Content\Fonts\Roboto\" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Content\Fonts\Roboto\Roboto-Regular.ttf">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>