<Project>
	<PropertyGroup>
		<Configurations>Debug DesktopVK;Debug WindowsDX12;Release DesktopVK;Release WindowsDX12</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug DesktopVK' Or '$(Configuration)' == 'Release DesktopVK'">
		<TargetFramework>net10.0</TargetFramework>
		<MonoGamePlatform>DesktopVK</MonoGamePlatform>
		<DefineConstants>$(DefineConstants);DESKTOPVK</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Debug WindowsDX12' Or '$(Configuration)' == 'Release WindowsDX12'">
		<TargetFramework>net10.0-windows</TargetFramework>
		<MonoGamePlatform>WindowsDX12</MonoGamePlatform>
		<DefineConstants>$(DefineConstants);WINDOWSDX12</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug DesktopVK' Or '$(Configuration)' == 'Debug WindowsDX12'">
		<Optimize>False</Optimize>
		<DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release DesktopVK' Or '$(Configuration)' == 'Release WindowsDX12'">
		<Optimize>True</Optimize>
		<DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
	</PropertyGroup>
</Project>