name: Validation Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v5

    - name: Run Tests
      run: dotnet test
      working-directory: ./src
      env:
        NuGetPackageSourceCredentials_github_sdcondon: Username=sdcondon;Password=${{ secrets.PACKAGE_PAT }}